version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: mysql://user:password@db:3306/database
      JWT_SECRET: secret
    ports:
      - 8080:3000
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:7.2.3
    restart: always
